(load "2.2-start-point.scm")
(load "2.2-end-point.scm")
(define (print-point x)
   (newline)
   (display "(")
   (display (start-point x))
   (display ",")
   (display (end-point x))
   (display ")"))
