(define (transpose m)
   (define (car-n x)
      (map car x))
   (define (cdr-n x)
      (map cdr x))
   (define (fringe x)
      (cond ((null? x) ())
            ((not (pair? x)) (list x))
            (else (append (fringe (car x)) (fringe (cdr x))))))
   (cond ((null? (fringe m)) ())
         (else (cons (car-n m) (transpose (cdr-n m))))))
