(load "2.46-make-vect.scm")
(load "2.48-middle-vect.scm")
(load "p93-segment-painter.scm")
(load "2.49-middle-vect.scm")
(define (frame-painter)
  (define top-left (make-vect 0.0 1.0))
  (define top-right (make-vect 1.0 1.0))
  (define bottom-left (make-vect 0.0 0.0))
  (define bottom-right (make-vect 1.0 0.0))
  (define top (middle-vect top-left top-right))
  (define left (middle-vect top-left bottom-left))
  (define right (middle-vect top-right bottom-right))
  (define bottom (middle-vect bottom-left bottom-right))
  (define segment-list (list top left right bottom))
  (segments->painter segment-list))
