(load "2.46-make-vect.scm")
(load "2.48-make-segment.scm")
(load "p93-segment-painter.scm")
(define (frame-painter)
  (define top-left (make-vect 0.0 1.0))
  (define top-right (make-vect 1.0 1.0))
  (define bottom-left (make-vect 0.0 0.0))
  (define bottom-right (make-vect 1.0 0.0))
  (define top (make-segment top-left top-right))
  (define left (make-segment top-left bottom-left))
  (define right (make-segment top-right bottom-right))
  (define bottom (make-segment bottom-left bottom-right))
  (define segment-list (list top left right bottom))
  (segments->painter segment-list))
