(load "2.63-tree-list1.scm")
(load "2.63-tree-list2.scm")
(define (test)
  (define a (list 1 () ()))
  (define b (list 3 () ()))
  (define c (list 5 () ()))
  (define d (list 7 () ()))
  (define a1 (list 2 a b))
  (define a2 (list 6 c d))
  (define x (list 4 a1 a2))
  (display (tree->list-1 x))
  (newline)
  (display (tree->list-2 x)))
