(load "p119-tag.scm")
(load "p123-put-and-get.scm")
(load "p124-rectangular.scm")
(load "p124-polar.scm")

(define (install-complex-package)
  (define (make-from-real-imag x y)
    ((get 'make-from-real-imag 'rectangular) x y))
  (define (make-from-mag-ang r a)
    ((get 'make-from-mag-ang 'polar) r a))

  (define (add-complex x y)
    (make-from-real-imag (+ (real_part_ x) (real_part_ y))
			 (+ (imag_part_ x) (imag_part_ y))))
  (define (sub-complex x y)
    (make-from-real-imag (- (real-part_ x) (real-part_ y))
			 (- (imag-part_ x) (imag-part_ y))))
  (define (mul-complex x y)
    (make-from-mag-ang (* (magnitude_ x) (magnitude_ y))
		       (+ (angle_ x) (angle_ y))))
  (define (div-complex x y)
    (make-from-mag-ang (/ (magnitude_ x) (magnitude_ y))
		       (- (angle_ x) (angle_ y))))

  (define (tag z) (attach-tag 'complex z))
  (put 'add '(complex complex)
       (lambda (x y) (tag (add-complex x y))))
  (put 'sub '(complex complex)
       (lambda (x y) (tag (sub-complex x y))))
  (put 'mul '(complex complex)
       (lambda (x y) (tag (mul-complex x y))))
  (put 'div '(complex complex)
       (lambda (x y) (tag (div-complex x y))))
  (put 'real-part_ '(complex) real-part_)
  (put 'imag-part_ '(complex) imag-part_)
  (put 'magnitude_ '(complex) magnitude_)
  (put 'angle_ '(complex) angle_)
  (put 'make-from-real-imag 'complex
       (lambda (x y) (tag (make-from-real-imag x y))))
  (put 'make-from-mag-ang 'complex
       (lambda (x y) (tag (make-from-mag-ang x y))))
  'done)

(define (make-complex-from-real-imag x y)
  ((get 'make-from-real-imag 'complex) x y))
(define (make-complex-from-mag-ang r a)
  ((get 'make-from-mag-ang 'complex) x y))
