(define (make-sum a1 a2)
  (display "make-sum ")
  (display a1)
  (display "  ")
  (display a2)
  (newline)
  (cond ((and (and (number? a1) (= a1 0)) (and (number? a2) (= a2 0))) 0)
	((and (number? a1) (= a1 0)) a2)
	((and (number? a2) (= a2 0)) a1)
	((and (not (number? a1)) (number? a2) (< a2 0)) (list a1 '- (- a2)))
	((and (not (number? a2)) (number? a1) (< a1 0)) (list a2 '- (- a1)))
        ((and (number? a1) (number? a2)) (+ a1 a2))
	(else (list a1 '+ a2))))
