(load "2.58b-product.scm")
(load "2.58b-sum.scm")
(load "2.58b-multiplicand.scm")
(load "2.58b-multiplier.scm")
(load "2.58b-addend.scm")
(load "2.58b-augend.scm")
(define (change-style items)
    (if (pair? items)
      (cond ((sum? items) (begin (let ((a1 (addend items))
				       (a2 (augend items)))
				   (display a1)
				   (newline)
				   (display a2)
				   (newline)
				   (let ((a1 (change-style a1))
					 (a2 (change-style a2)))
				     (cond ((and (pair? a1) (pair? a2)) (append a1 (append (list '+) a2)))
					   ((pair? a1) (append a1 (list '+ a2)))
					   ((pair? a2) (append (list a1 '+) a2))
					   (else (list a1 '+ a2)))))))
	    ((product? items) (let ((a1 (multiplier items))
				    (a2 (multiplicand items)))
				(display a1)
				(newline)
				(display a2)
				(newline)
				(list (change-style a1) '* (change-style a2))))
	    (else items))
      items))
