(load "2.58b-addend.scm")
(load "2.58b-augend.scm")
(load "2.58b-make-product.scm")
(load "2.58b-multiplicand.scm")
(load "2.58b-multiplier.scm")
(load "2.58b-sum.scm")
(load "2.58b-variable.scm")
(load "2.58b-same-variable.scm")
(load "2.58b-product.scm")
(load "2.58b-make-sum.scm")
(load "2.58b-exponentiation.scm")
(load "2.58b-base.scm")
(load "2.58b-exponent.scm")
(load "2.58b-make-exponentiation.scm")
(define (deriv expression var)
  (display "deriv ")
  (display expression)
  (display "  ")
  (display var)
  (newline)
  (cond ((number? expression) 0)
	((variable? expression)
	 (display "variable ")
	 (display expression)
	 (newline)
	 (if (same-variable? expression var) 
	     1 
	     0))
	((sum? expression) 
	 (display "sum ")
	 (display expression)
	 (newline)
	 (make-sum (deriv (addend expression) var)
		   (deriv (augend expression) var)))
	((product? expression)
	 (display "product ")
	 (display expression)
	 (newline)
	 (make-sum
	   (make-product (multiplier expression)
			 (deriv (multiplicand expression) var))
	   (make-product (deriv (multiplier expression) var)
			 (multiplicand expression))))
	((exponentiation? expression)
	 (let ((b (base expression))
	       (e (exponent expression)))
	   (let ((new-e (make-sum e (- 1)))
		 (new-b (deriv b var)))
	     (cond ((and (number? (deriv e var)) (= (deriv e var) 0)) (make-product e (make-product new-b (make-exponentiation b new-e))))
		   (else (error "not know what to do" expression))))))
	(else (error "unknown expression type --- DERIV" expression))))
