(load "queue2.scm")
(define haha (make-queue))
(insert-queue! haha 2)
(display haha)
(newline)
(insert-queue! haha 3)
(display haha)
(newline)
(insert-queue! haha 4)
(display haha)
(newline)
(delete-queue! haha)
(display haha)
(newline)
(delete-queue! haha)
(display haha)
(newline)
(delete-queue! haha)
(display haha)
(newline)
