(define (sqrt x)
 (define (average a b)
  (/ (+ a b) 2))
 (define (improve guess x)
  (average (/ x guess) guess))
 (define (square a)
  (* a a))
 (define (close-enough? guess x)
  (< (abs (- x (square guess))) 0.000001))
 (define (sqrt-iter guess x)
  (display guess)
  (newline)
  (if (close-enough? guess x)
   guess
   (sqrt-iter (improve guess x) x)))
 (sqrt-iter 1.0 x))
