(load "p124-rectangular.scm")
(load "p124-polar.scm")
(load "p124-apply-generic.scm")

(define (test) 
  (display "well prepared.")
  (newline)
  (install-rectangular-package)
  (display "well prepared.")
  (newline)
  (install-polar-package)
  (display "well prepared.")
  (newline)
  (define a (make-from-real-imag 3 4))
  (display (magnitude_ a)))
