(load "2.65-left-branch.scm")
(load "2.65-right-branch.scm")
(load "2.65-entry.scm")
(define (tree->list-1 tree)
  (if (null? tree)
    ()
    (append (tree->list-1 (left-branch tree)) (cons (entry tree) (tree->list-1 (right-branch tree))))))
