(define (make-product a1 a2) 
  (display "make-product ")
  (display a1)
  (display "  ")
  (display a2)
  (newline)
  (cond ((or (and (number? a1) (= a1 0)) (and (number? a2) (= a2 0))) 0)
        ((and (and (number? a1) (= a1 1)) (not (number? a2))) a2)
	((and (and (number? a2) (= a2 1)) (not (number? a1))) a1)
	((and (number? a1) (number? a2)) (* a1 a2))
	(else (list '* a1 a2))))
