(load "2.57-single-operand.scm")
(define (make-sum a1 . a2)
  (display "make-sum ")
  (display a1)
  (display "  ")
  (display a2)
  (newline)
  (if (single-operand? a2)
      (let ((a2 (car a2)))
	(cond ((and (number? a1) (= a1 0)) a2)
	      ((and (number? a2) (= a2 0)) a1)
	      ((and (number? a1) (number? a2)) (+ a1 a2))
	      (else (list '+ a1 a2))))
      (cons '+ (cons a1 a2))))
