(load "2.57-make-product.scm")
(load "2.57-single-operand.scm")
(define (multiplicand p)
  (display "multiplicand ")
  (display (cddr p))
  (newline) 
  (let ((a2 (cddr p)))
    (if (single-operand? a2)
        (car a2)
	(apply make-product a2))))
