(define (e k)
   (define (d i)
      (if (= 0 (remainder (+ i 1) 3))
          (* 2.0 (/ (+ i 1) 3))
          1.0))
   (define (n i) 1.0)
   (define (try i) 
      (if (= k i)
          (/ (n i) (d i))
          (/ (n i) (+ (d i) (try (+ i 1))))))
   (+ 2.0 (try 1)))
