(define (fixed-point f first-guess)
   (define (close-enough? v1 v2) (< (abs (- v1 v2)) 0.00001))
   (define (report guess step)
      (display "Step: ")
      (display step)
      (display "\t")
      (display "Guess: ")
      (display guess)
      (newline))
   (define (try guess step)
      (report guess step)
      (let ((next (f guess)))
         (if (close-enough? guess next)
             (begin (report next (+ step 1))
                    next)
             (try next (+ step 1)))))
   (try first-guess 1))
