(load "p186-table-two-dimension.scm")

(define (test)
  (define t (make-table))
  (insert! 'math '+ 43 t)
  (display t)
  (newline)
  (insert! 'math '- 45 t)
  (display t)
  (newline)
  (insert! 'math '* 42 t)
  (display t)
  (newline)
  (insert! 'letters 'a 97 t)
  (display t)
  (newline)
  (insert! 'letters 'b 98 t)
  (display t)
  (newline)
  (lookup 'letters 'a t)
  (print-table t))
