(define (delay proc)
  (define (memo-proc proc)
    (let ((already-run? false)
	  (result false))
      (lambda ()
	(if (not already-run?)
	  (begin (set! result (proc))
		 (set! already-run? true)
		 result)
	  result))))
  (memo-proc (lambda () (proc))))

(define (force delayed-object)
  (delayed-object))
