(define (make-queue)
  (let ((front-ptr '())
	(rear-ptr '()))
    (define (empty-queue?)
      (null? front-ptr))
    (define (insert-queue! item)
      (let ((new-pair (cons item '())))
	(cond ((empty-queue?)
	       (set! front-ptr new-pair)
	       (set! rear-ptr new-pair)
	       front-ptr)
	      (else 
		(set-cdr! rear-ptr new-pair)
		(set! rear-ptr new-pair)
		front-ptr))))
    (define (delete-queue!)
      (cond ((empty-queue?) 
	     (error "DELETE! called with an empty queue" front-ptr))
	    (else
	      (set! front-ptr (cdr front-ptr))
	      front-ptr)))
    (define (dispatch m)
      (cond ((eq? m 'insert-queue!)
	     insert-queue!)
	    ((eq? m 'delete-queue!)
	     (delete-queue!))
	    ;;;这里delete-queue!之所以要加括号是因为define部分加了括号，若改成define delete-queue！即可不加括号。
	    ((eq? m 'front-ptr)
	     front-ptr)
	    ((eq? m 'rear-ptr)
	     rear-ptr)
	    (else 
	      (error "no such operation -- MAKE-QUEUE" m))))
    dispatch))

